[platformio]
default_envs = toggle-test-led-5s
src_dir = ${PROJECT_DIR}/${PIOENV}/src
lib_dir = lib

[env]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
upload_speed = 57600 ; <--- Sets the default for all envs to use old bootloader
lib_extra_dirs = lib

[env:toggle-test-led-5s]

[env:toggle-pin-3-5s]

[env:motor-control-TB6612FNG]